MVC_Contactos/Models/ModeloPersona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC_Contactos.Models
{
    public class ModeloPersona
    {
        //creamos estructura de los datos
        [Key]
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }

    }
}

MVC_Contactos/Controllers/CRUD_PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using MVC_Contactos.Models;

namespace MVC_Contactos.Controllers
{
    public class CRUD_PersonaController : Controller
    {
        //Creamos la variable de almacenamiento de la lista de personas
        public static List<ModeloPersona> ListaPersonas = new List<ModeloPersona>()
        {
            new ModeloPersona() {PersonaId = 1, Nombre = "Andrés Gómez", Telefono = "3005776492", Email = "andres@gmail.com"},
            new ModeloPersona() {PersonaId = 2, Nombre = "Salomé Acosta", Telefono = "3218437554", Email = "salome@gmail.com"},
            new ModeloPersona() { PersonaId = 3, Nombre = "Jorge Montoya", Telefono = "3005776322", Email = "jorge@gmail.com"},
            new ModeloPersona() { PersonaId = 4, Nombre = "Samuel Martinéz", Telefono = "3247764921", Email = "samuel@gmail.com"}
        };   

        // GET: CRUD_Persona
        public ActionResult Index()
        {
            return View(ListaPersonas);//Importante para ejecución de Model
        }

        public ActionResult Nuevo()
        {
            return View();
        }

        [HttpPost] //recibe los datos para el registro de nuevo ingreso

        public ActionResult Nuevo(FormCollection collection)
        {
            Random random = new Random();

            var Persona = new ModeloPersona();
            Persona.PersonaId = random.Next(10, 99);
            Persona.Nombre = collection["Nombre"];
            Persona.Telefono = collection["Telefono"];
            Persona.Email = collection["Email"];
            ListaPersonas.Add(Persona);

            return RedirectToAction("Index");
        }

        /*-------------------------EDITAR--------------------------------*/
        //GET: CRUD_Persona editar
        public ActionResult Editar(int id = 0)
        {
            var Persona = ListaPersonas.Single(m => m.PersonaId == id);
            return View(Persona);

        }

        //GET: CRUD_Persona editar recibe datos a modificar
        [HttpPost]
        public ActionResult Editar(FormCollection collection)
        {
            var persona = ListaPersonas.Single(m => m.PersonaId == int.Parse(collection["PersonaId"]));
            if (TryUpdateModel(persona))
            {
                persona.Nombre = collection["Nombre"];
                persona.Telefono = collection["Telefono"];
                persona.Email = collection["Email"];
            }
            return RedirectToAction("Index");
        }

        /*-------------------------BORRAR--------------------------------*/
        public ActionResult Borrar(int id = 0)
        {
            var Persona = ListaPersonas.Single(m => m.PersonaId == id);
            return View(Persona);

        }

        [HttpPost]
        public ActionResult BorrarConfirmado(FormCollection collection)
        {
            var persona = ListaPersonas.Single(m => m.PersonaId == int.Parse(collection["PersonaId"]));
            ListaPersonas.Remove(persona);
            return RedirectToAction("Index");
        }
    }
}

MVC_Contactos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Contactos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC_Contactos/Views/CRUD_Persona/Borrar.cshtml
@model MVC_Contactos.Models.ModeloPersona

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar</h2>

<div>
    <p> ID: @Model.PersonaId</p>
    <p>Nombre: @Model.Nombre</p>
    <p>Telefono: @Model.Telefono</p>
    <p>Correo: @Model.Email</p>

    <form method="post" action="/CRUD_Persona/BorrarConfirmado">
        <input type="hidden" name="PersonaId" value="@Model.PersonaId" />
        <br />
        <input type="submit" value="BORRAR" class="btn btn-danger" />     <a class="btn btn-info" href="/CRUD_Persona">Retornar</a>
    </form>

</div>

MVC_Contactos/Views/CRUD_Persona/Editar.cshtml
@model MVC_Contactos.Models.ModeloPersona

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

<div>
    <form method="post" action="/CRUD_Persona/Editar">
        <input type="hidden" name="PersonaId" value="@Model.PersonaId" />
        <br />
        Nombre:
        <input type="text" name="Nombre" value="@Model.Nombre" />
        <br />
        Telefono:
        <input type="text" name="Telefono" value="@Model.Telefono" />
        <br />
        Correo:
        <input type="text" name="Email" value="@Model.Email" />
        <br />
        <input type="submit" value="GUARDAR" />     <a class="btn btn-info" href="/CRUD_Persona">Retornar</a>
    </form>
</div>

MVC_Contactos/Views/CRUD_Persona/Index.cshtml
@model List<MVC_Contactos.Models.ModeloPersona>

@{
    ViewBag.titulo = "Administración de personas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.titulo</h2>

<a href="~/CRUD_Persona/Nuevo" class="btn btn-success">NUEVO EMPLEADO</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>PersonaId</th>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>OPCIONES</th>
        </tr>
    </thead>
    <tbody>
         @foreach (var item in Model) 
         {
        <tr>
            <th>@Html.DisplayFor(modelItem => item.PersonaId)</th>
            <th>@Html.DisplayFor(modelItem => item.Nombre)</th>
            <th>@Html.DisplayFor(modelItem => item.Telefono)</th>
            <th>@Html.DisplayFor(modelItem => item.Email)</th>
            <th>
                <a href="/CRUD_Persona/Editar/@item.PersonaId" class="btn btn-info">EDITAR</a>
                <a href="/CRUD_Persona/Borrar//@item.PersonaId" class="btn btn-danger">BORRAR</a>
            </th>
        </tr>
         }
    </tbody>
</table>

MVC_Contactos/Views/CRUD_Persona/Nuevo.cshtml
@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nuevo</h2>

<div>
    <form method="post" action="/CRUD_Persona/Nuevo">
        <input type="hidden" name="PersonaId" value="" />
        <br />
        Nombre:
        <input type="text" name="Nombre" value="" />
        <br />
        Telefono:
        <input type="text" name="Telefono" value="" />
        <br />
        Correo:
        <input type="text" name="Email" value="" />
        <br />
        <input type="submit" value="GUARDAR" />     <a class="btn btn-info" href="/CRUD_Persona">Retornar</a>
    </form>
</div>

MVC_Contactos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>Acerca de</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC_Contactos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Bienvenidos a contacto</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC_Contactos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>INFORCEAN</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVC_Contactos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Personas", "Index", "CRUD_Persona")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Aplicación desarrollada y soportada por Andrés Gómez</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>